<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<Platforms>ARM64</Platforms>

		<!-- Manifest Config -->
		<UniqueId>NRTnarathip.ImproveGame</UniqueId>
		<Name>Improve Game</Name>
		<Authors>NRTnarathip</Authors>
		<Description>Support The Mod Language</Description>
		<Version>2.0.2</Version>
		<MinimumApiVersion>4.1.7</MinimumApiVersion>

		<!--Build Config-->
		<EnableModDeploy>false</EnableModDeploy>
		<EnableHarmony>true</EnableHarmony>

	</PropertyGroup>

	<ItemGroup>
		<!-- Mod Dependencies -->
		<SMAPIDependency Include="NRTnarathip.VirtualKeyboard" Required="false" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Leclair.Stardew.ModManifestBuilder" Version="2.4.1" />
		<PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
	</ItemGroup>

	<ItemGroup>
		<None Update="manifest.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="&quot;$(ProjectDir)PostBuild.cmd&quot;" />
	</Target>
</Project>
